name: learn-github-actions
on: [push]
jobs:
  # check-bats-version:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses:
      # - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'
      # - run: npm install -g bats
      # - run: bats -v
  linting-code:
    runs-on: ubuntu-latest
    steps:
      - name: Python Linter
        uses: sunnysid3up/python-linter@v0.1-beta.7
        with:
          source: "DjangoGitAction"
